# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grudi.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 623)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 621))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSearch = QtWidgets.QWidget()
        self.tabSearch.setObjectName("tabSearch")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabSearch)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 450, 111, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelFound = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelFound.setObjectName("labelFound")
        self.horizontalLayout_4.addWidget(self.labelFound)
        self.lineEditFound = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditFound.setReadOnly(True)
        self.lineEditFound.setClearButtonEnabled(False)
        self.lineEditFound.setObjectName("lineEditFound")
        self.horizontalLayout_4.addWidget(self.lineEditFound)
        self.formLayoutWidget = QtWidgets.QWidget(self.tabSearch)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 761, 155))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutSearch = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutSearch.setContentsMargins(0, 0, 0, 0)
        self.formLayoutSearch.setObjectName("formLayoutSearch")
        self.labelAccessToken = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelAccessToken.setObjectName("labelAccessToken")
        self.formLayoutSearch.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelAccessToken)
        self.lineAccessToken = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineAccessToken.setObjectName("lineAccessToken")
        self.formLayoutSearch.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineAccessToken)
        self.labelAccessTokenSecret = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelAccessTokenSecret.setObjectName("labelAccessTokenSecret")
        self.formLayoutSearch.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelAccessTokenSecret)
        self.lineAccessTokenSecret = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineAccessTokenSecret.setObjectName("lineAccessTokenSecret")
        self.formLayoutSearch.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineAccessTokenSecret)
        self.labelConsumerKey = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelConsumerKey.setObjectName("labelConsumerKey")
        self.formLayoutSearch.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelConsumerKey)
        self.lineConsumerKey = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineConsumerKey.setObjectName("lineConsumerKey")
        self.formLayoutSearch.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineConsumerKey)
        self.labelConsumerSecret = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelConsumerSecret.setObjectName("labelConsumerSecret")
        self.formLayoutSearch.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelConsumerSecret)
        self.lineConsumerSecret = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineConsumerSecret.setObjectName("lineConsumerSecret")
        self.formLayoutSearch.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineConsumerSecret)
        self.lineDatabasePathSearch = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineDatabasePathSearch.setObjectName("lineDatabasePathSearch")
        self.formLayoutSearch.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineDatabasePathSearch)
        self.labelSearchTerms = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelSearchTerms.setObjectName("labelSearchTerms")
        self.formLayoutSearch.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelSearchTerms)
        self.lineSearchTerms = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineSearchTerms.setObjectName("lineSearchTerms")
        self.formLayoutSearch.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineSearchTerms)
        self.pushButtonDatabasePathSearch = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButtonDatabasePathSearch.setObjectName("pushButtonDatabasePathSearch")
        self.formLayoutSearch.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButtonDatabasePathSearch)
        self.textEditOutput = QtWidgets.QTextEdit(self.tabSearch)
        self.textEditOutput.setEnabled(True)
        self.textEditOutput.setGeometry(QtCore.QRect(10, 210, 761, 231))
        self.textEditOutput.setReadOnly(True)
        self.textEditOutput.setObjectName("textEditOutput")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabSearch)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(330, 500, 160, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchPushButtonSearch = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.searchPushButtonSearch.setCheckable(False)
        self.searchPushButtonSearch.setChecked(False)
        self.searchPushButtonSearch.setAutoDefault(False)
        self.searchPushButtonSearch.setDefault(False)
        self.searchPushButtonSearch.setFlat(False)
        self.searchPushButtonSearch.setObjectName("searchPushButtonSearch")
        self.horizontalLayout_3.addWidget(self.searchPushButtonSearch)
        self.cancelPushButtonSearch = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelPushButtonSearch.setObjectName("cancelPushButtonSearch")
        self.horizontalLayout_3.addWidget(self.cancelPushButtonSearch)
        self.labelGrudi = QtWidgets.QLabel(self.tabSearch)
        self.labelGrudi.setGeometry(QtCore.QRect(620, 470, 131, 71))
        self.labelGrudi.setText("")
        self.labelGrudi.setPixmap(QtGui.QPixmap("grudilogo.png"))
        self.labelGrudi.setScaledContents(True)
        self.labelGrudi.setObjectName("labelGrudi")
        self.tabWidget.addTab(self.tabSearch, "")
        self.tabExport = QtWidgets.QWidget()
        self.tabExport.setObjectName("tabExport")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tabExport)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(350, 460, 191, 91))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.exportPushButtonExport = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.exportPushButtonExport.setCheckable(False)
        self.exportPushButtonExport.setChecked(False)
        self.exportPushButtonExport.setAutoDefault(False)
        self.exportPushButtonExport.setDefault(False)
        self.exportPushButtonExport.setFlat(False)
        self.exportPushButtonExport.setObjectName("exportPushButtonExport")
        self.horizontalLayout_5.addWidget(self.exportPushButtonExport)
        self.progressBarExport = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        self.progressBarExport.setProperty("value", 24)
        self.progressBarExport.setObjectName("progressBarExport")
        self.horizontalLayout_5.addWidget(self.progressBarExport)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tabExport)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 761, 51))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayoutSearch_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayoutSearch_2.setContentsMargins(0, 0, 0, 0)
        self.formLayoutSearch_2.setObjectName("formLayoutSearch_2")
        self.pushButtonDatabasePathExport = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButtonDatabasePathExport.setObjectName("pushButtonDatabasePathExport")
        self.formLayoutSearch_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButtonDatabasePathExport)
        self.lineDatabasePathExport = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineDatabasePathExport.setObjectName("lineDatabasePathExport")
        self.formLayoutSearch_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineDatabasePathExport)
        self.labelFieldsExport = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.labelFieldsExport.setObjectName("labelFieldsExport")
        self.formLayoutSearch_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelFieldsExport)
        self.lineFieldsExport = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineFieldsExport.setObjectName("lineFieldsExport")
        self.formLayoutSearch_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineFieldsExport)
        self.comboBoxSelectTable = QtWidgets.QComboBox(self.tabExport)
        self.comboBoxSelectTable.setGeometry(QtCore.QRect(10, 70, 91, 20))
        self.comboBoxSelectTable.setObjectName("comboBoxSelectTable")
        self.comboBoxSelectTable.addItem("")
        self.tabWidget.addTab(self.tabExport, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grudi Twitter Tool"))
        self.labelFound.setText(_translate("MainWindow", "Found:"))
        self.labelAccessToken.setText(_translate("MainWindow", "Access Token:"))
        self.labelAccessTokenSecret.setText(_translate("MainWindow", "Access Token Secret:"))
        self.labelConsumerKey.setText(_translate("MainWindow", "Consumer Key:"))
        self.labelConsumerSecret.setText(_translate("MainWindow", "Consumer Secret:"))
        self.labelSearchTerms.setText(_translate("MainWindow", "Search terms, separated by \',\':"))
        self.pushButtonDatabasePathSearch.setText(_translate("MainWindow", "SQLite3 Database path:"))
        self.searchPushButtonSearch.setText(_translate("MainWindow", "Search"))
        self.cancelPushButtonSearch.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("MainWindow", "Search"))
        self.exportPushButtonExport.setText(_translate("MainWindow", "Export"))
        self.pushButtonDatabasePathExport.setText(_translate("MainWindow", "SQLite3 Database path:"))
        self.labelFieldsExport.setText(_translate("MainWindow", "Fields, separated by \',\':"))
        self.comboBoxSelectTable.setItemText(0, _translate("MainWindow", "Select table:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExport), _translate("MainWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
