# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tweetwatcher.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(844, 608)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/fuck you/Desktop/1582834885184.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 801, 571))
        self.tabWidget.setMaximumSize(QtCore.QSize(801, 571))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSearch = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSearch.sizePolicy().hasHeightForWidth())
        self.tabSearch.setSizePolicy(sizePolicy)
        self.tabSearch.setObjectName("tabSearch")
        self.textEditOutput = QtWidgets.QTextEdit(self.tabSearch)
        self.textEditOutput.setEnabled(True)
        self.textEditOutput.setGeometry(QtCore.QRect(9, 189, 781, 271))
        self.textEditOutput.setReadOnly(True)
        self.textEditOutput.setObjectName("textEditOutput")
        self.widget = QtWidgets.QWidget(self.tabSearch)
        self.widget.setGeometry(QtCore.QRect(9, 9, 781, 180))
        self.widget.setObjectName("widget")
        self.formLayoutSearch = QtWidgets.QFormLayout(self.widget)
        self.formLayoutSearch.setContentsMargins(0, 0, 0, 0)
        self.formLayoutSearch.setObjectName("formLayoutSearch")
        self.labelAccessToken = QtWidgets.QLabel(self.widget)
        self.labelAccessToken.setObjectName("labelAccessToken")
        self.formLayoutSearch.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelAccessToken)
        self.lineAccessToken = QtWidgets.QLineEdit(self.widget)
        self.lineAccessToken.setReadOnly(False)
        self.lineAccessToken.setObjectName("lineAccessToken")
        self.formLayoutSearch.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineAccessToken)
        self.labelAccessTokenSecret = QtWidgets.QLabel(self.widget)
        self.labelAccessTokenSecret.setObjectName("labelAccessTokenSecret")
        self.formLayoutSearch.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelAccessTokenSecret)
        self.lineAccessTokenSecret = QtWidgets.QLineEdit(self.widget)
        self.lineAccessTokenSecret.setObjectName("lineAccessTokenSecret")
        self.formLayoutSearch.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineAccessTokenSecret)
        self.labelConsumerKey = QtWidgets.QLabel(self.widget)
        self.labelConsumerKey.setObjectName("labelConsumerKey")
        self.formLayoutSearch.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelConsumerKey)
        self.lineConsumerKey = QtWidgets.QLineEdit(self.widget)
        self.lineConsumerKey.setObjectName("lineConsumerKey")
        self.formLayoutSearch.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineConsumerKey)
        self.labelConsumerSecret = QtWidgets.QLabel(self.widget)
        self.labelConsumerSecret.setObjectName("labelConsumerSecret")
        self.formLayoutSearch.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelConsumerSecret)
        self.lineConsumerSecret = QtWidgets.QLineEdit(self.widget)
        self.lineConsumerSecret.setObjectName("lineConsumerSecret")
        self.formLayoutSearch.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineConsumerSecret)
        self.pushButtonDatabasePathSearch = QtWidgets.QPushButton(self.widget)
        self.pushButtonDatabasePathSearch.setObjectName("pushButtonDatabasePathSearch")
        self.formLayoutSearch.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButtonDatabasePathSearch)
        self.lineDatabasePathSearch = QtWidgets.QLineEdit(self.widget)
        self.lineDatabasePathSearch.setObjectName("lineDatabasePathSearch")
        self.formLayoutSearch.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineDatabasePathSearch)
        self.labelSearchTerms = QtWidgets.QLabel(self.widget)
        self.labelSearchTerms.setObjectName("labelSearchTerms")
        self.formLayoutSearch.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelSearchTerms)
        self.lineSearchTerms = QtWidgets.QLineEdit(self.widget)
        self.lineSearchTerms.setObjectName("lineSearchTerms")
        self.formLayoutSearch.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineSearchTerms)
        self.labelStorage = QtWidgets.QLabel(self.widget)
        self.labelStorage.setObjectName("labelStorage")
        self.formLayoutSearch.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelStorage)
        self.horizontalLayoutStorageRadioButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutStorageRadioButtons.setObjectName("horizontalLayoutStorageRadioButtons")
        self.radioButtonSaveSingle = QtWidgets.QRadioButton(self.widget)
        self.radioButtonSaveSingle.setObjectName("radioButtonSaveSingle")
        self.horizontalLayoutStorageRadioButtons.addWidget(self.radioButtonSaveSingle)
        self.radioButtonSaveSeparatedly = QtWidgets.QRadioButton(self.widget)
        self.radioButtonSaveSeparatedly.setObjectName("radioButtonSaveSeparatedly")
        self.horizontalLayoutStorageRadioButtons.addWidget(self.radioButtonSaveSeparatedly)
        self.radioButtonDontSave = QtWidgets.QRadioButton(self.widget)
        self.radioButtonDontSave.setObjectName("radioButtonDontSave")
        self.horizontalLayoutStorageRadioButtons.addWidget(self.radioButtonDontSave)
        self.formLayoutSearch.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayoutStorageRadioButtons)
        self.widget1 = QtWidgets.QWidget(self.tabSearch)
        self.widget1.setGeometry(QtCore.QRect(10, 470, 142, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelFound = QtWidgets.QLabel(self.widget1)
        self.labelFound.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelFound.setObjectName("labelFound")
        self.horizontalLayout_4.addWidget(self.labelFound)
        self.lineEditFound = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFound.sizePolicy().hasHeightForWidth())
        self.lineEditFound.setSizePolicy(sizePolicy)
        self.lineEditFound.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditFound.setReadOnly(True)
        self.lineEditFound.setClearButtonEnabled(False)
        self.lineEditFound.setObjectName("lineEditFound")
        self.horizontalLayout_4.addWidget(self.lineEditFound)
        self.widget2 = QtWidgets.QWidget(self.tabSearch)
        self.widget2.setGeometry(QtCore.QRect(0, 500, 791, 25))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchPushButtonSearch = QtWidgets.QPushButton(self.widget2)
        self.searchPushButtonSearch.setCheckable(False)
        self.searchPushButtonSearch.setChecked(False)
        self.searchPushButtonSearch.setAutoDefault(False)
        self.searchPushButtonSearch.setDefault(False)
        self.searchPushButtonSearch.setFlat(False)
        self.searchPushButtonSearch.setObjectName("searchPushButtonSearch")
        self.horizontalLayout_3.addWidget(self.searchPushButtonSearch)
        self.cancelPushButtonSearch = QtWidgets.QPushButton(self.widget2)
        self.cancelPushButtonSearch.setObjectName("cancelPushButtonSearch")
        self.horizontalLayout_3.addWidget(self.cancelPushButtonSearch)
        self.tabWidget.addTab(self.tabSearch, "")
        self.tabExport = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabExport.sizePolicy().hasHeightForWidth())
        self.tabExport.setSizePolicy(sizePolicy)
        self.tabExport.setObjectName("tabExport")
        self.gridLayout = QtWidgets.QGridLayout(self.tabExport)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exportPushButtonExport = QtWidgets.QPushButton(self.tabExport)
        self.exportPushButtonExport.setCheckable(False)
        self.exportPushButtonExport.setChecked(False)
        self.exportPushButtonExport.setAutoDefault(False)
        self.exportPushButtonExport.setDefault(False)
        self.exportPushButtonExport.setFlat(False)
        self.exportPushButtonExport.setObjectName("exportPushButtonExport")
        self.horizontalLayout_2.addWidget(self.exportPushButtonExport)
        self.cancelPushButtonExport = QtWidgets.QPushButton(self.tabExport)
        self.cancelPushButtonExport.setObjectName("cancelPushButtonExport")
        self.horizontalLayout_2.addWidget(self.cancelPushButtonExport)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pushButtonDatabasePathExport = QtWidgets.QPushButton(self.tabExport)
        self.pushButtonDatabasePathExport.setObjectName("pushButtonDatabasePathExport")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButtonDatabasePathExport)
        self.lineDatabasePathExport = QtWidgets.QLineEdit(self.tabExport)
        self.lineDatabasePathExport.setObjectName("lineDatabasePathExport")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineDatabasePathExport)
        self.labelFieldsExport = QtWidgets.QLabel(self.tabExport)
        self.labelFieldsExport.setObjectName("labelFieldsExport")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelFieldsExport)
        self.lineFieldsExport = QtWidgets.QLineEdit(self.tabExport)
        self.lineFieldsExport.setObjectName("lineFieldsExport")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineFieldsExport)
        self.labelLanguagesExport = QtWidgets.QLabel(self.tabExport)
        self.labelLanguagesExport.setObjectName("labelLanguagesExport")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelLanguagesExport)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxAll = QtWidgets.QCheckBox(self.tabExport)
        self.checkBoxAll.setChecked(True)
        self.checkBoxAll.setTristate(False)
        self.checkBoxAll.setObjectName("checkBoxAll")
        self.horizontalLayout.addWidget(self.checkBoxAll)
        self.lineEditLanguages = QtWidgets.QLineEdit(self.tabExport)
        self.lineEditLanguages.setEnabled(False)
        self.lineEditLanguages.setObjectName("lineEditLanguages")
        self.horizontalLayout.addWidget(self.lineEditLanguages)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.labelTable = QtWidgets.QLabel(self.tabExport)
        self.labelTable.setObjectName("labelTable")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelTable)
        self.comboBoxSelectTable = QtWidgets.QComboBox(self.tabExport)
        self.comboBoxSelectTable.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxSelectTable.setObjectName("comboBoxSelectTable")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxSelectTable)
        self.labelFormat = QtWidgets.QLabel(self.tabExport)
        self.labelFormat.setObjectName("labelFormat")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelFormat)
        self.comboBoxSelectFormat = QtWidgets.QComboBox(self.tabExport)
        self.comboBoxSelectFormat.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxSelectFormat.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxSelectFormat.setObjectName("comboBoxSelectFormat")
        self.comboBoxSelectFormat.addItem("")
        self.comboBoxSelectFormat.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBoxSelectFormat)
        self.labelSince = QtWidgets.QLabel(self.tabExport)
        self.labelSince.setObjectName("labelSince")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelSince)
        self.dateTimeSince = QtWidgets.QDateTimeEdit(self.tabExport)
        self.dateTimeSince.setMaximumSize(QtCore.QSize(125, 16777215))
        self.dateTimeSince.setObjectName("dateTimeSince")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateTimeSince)
        self.labelUntil = QtWidgets.QLabel(self.tabExport)
        self.labelUntil.setObjectName("labelUntil")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelUntil)
        self.dateTimeUntil = QtWidgets.QDateTimeEdit(self.tabExport)
        self.dateTimeUntil.setMaximumSize(QtCore.QSize(125, 16777215))
        self.dateTimeUntil.setObjectName("dateTimeUntil")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.dateTimeUntil)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabExport, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tweet Watcher"))
        self.labelAccessToken.setText(_translate("MainWindow", "Access Token:"))
        self.labelAccessTokenSecret.setText(_translate("MainWindow", "Access Token Secret:"))
        self.labelConsumerKey.setText(_translate("MainWindow", "Consumer Key:"))
        self.labelConsumerSecret.setText(_translate("MainWindow", "Consumer Secret:"))
        self.pushButtonDatabasePathSearch.setText(_translate("MainWindow", "SQLite3 Database path:"))
        self.labelSearchTerms.setToolTip(_translate("MainWindow", "Comma separated keywords, e.g. \"Trump,Bernie\" (without quotation marks)."))
        self.labelSearchTerms.setText(_translate("MainWindow", "Search terms:"))
        self.lineSearchTerms.setPlaceholderText(_translate("MainWindow", "corona,covid"))
        self.labelStorage.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose whether you want to save all tweets in a single database table, multiple tables or not save at all.</p><p>It takes time to assign tweets to different tables, so that option might miss a considerable number of incoming tweets.</p></body></html>"))
        self.labelStorage.setText(_translate("MainWindow", "Storage:"))
        self.radioButtonSaveSingle.setToolTip(_translate("MainWindow", "Ideal option for trending, high influx topics, e.g \"flu\" during a flu outbreak."))
        self.radioButtonSaveSingle.setText(_translate("MainWindow", "save tweets in a single table"))
        self.radioButtonSaveSeparatedly.setToolTip(_translate("MainWindow", "Ideal option for not so trendy, lower influx topics."))
        self.radioButtonSaveSeparatedly.setText(_translate("MainWindow", "save tweets separatedly"))
        self.radioButtonDontSave.setToolTip(_translate("MainWindow", "Just show tweets on the screen."))
        self.radioButtonDontSave.setText(_translate("MainWindow", "don\'t save anything"))
        self.labelFound.setText(_translate("MainWindow", "Found:"))
        self.searchPushButtonSearch.setText(_translate("MainWindow", "Search"))
        self.cancelPushButtonSearch.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("MainWindow", "Search"))
        self.exportPushButtonExport.setText(_translate("MainWindow", "Export"))
        self.cancelPushButtonExport.setText(_translate("MainWindow", "Cancel"))
        self.pushButtonDatabasePathExport.setText(_translate("MainWindow", "SQLite3 Database path:"))
        self.labelFieldsExport.setText(_translate("MainWindow", "Fields:"))
        self.lineFieldsExport.setPlaceholderText(_translate("MainWindow", "created_at, user.screen_name, retweeted_status.user.screen_name and text are in by default."))
        self.labelLanguagesExport.setText(_translate("MainWindow", "Languages:"))
        self.checkBoxAll.setText(_translate("MainWindow", "All"))
        self.lineEditLanguages.setPlaceholderText(_translate("MainWindow", "pt,en"))
        self.labelTable.setText(_translate("MainWindow", "Table:"))
        self.labelFormat.setText(_translate("MainWindow", "Format:"))
        self.comboBoxSelectFormat.setItemText(0, _translate("MainWindow", ".xlsx"))
        self.comboBoxSelectFormat.setItemText(1, _translate("MainWindow", ".csv"))
        self.labelSince.setText(_translate("MainWindow", "Since:"))
        self.labelUntil.setText(_translate("MainWindow", "Until:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExport), _translate("MainWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
