# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tweetwatcher.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 595)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/fuck you/Desktop/1582834885184.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(801, 571))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSearch = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSearch.sizePolicy().hasHeightForWidth())
        self.tabSearch.setSizePolicy(sizePolicy)
        self.tabSearch.setObjectName("tabSearch")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabSearch)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayoutSearch = QtWidgets.QFormLayout()
        self.formLayoutSearch.setObjectName("formLayoutSearch")
        self.labelAccessToken = QtWidgets.QLabel(self.tabSearch)
        self.labelAccessToken.setObjectName("labelAccessToken")
        self.formLayoutSearch.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelAccessToken)
        self.lineAccessToken = QtWidgets.QLineEdit(self.tabSearch)
        self.lineAccessToken.setReadOnly(False)
        self.lineAccessToken.setObjectName("lineAccessToken")
        self.formLayoutSearch.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineAccessToken)
        self.labelAccessTokenSecret = QtWidgets.QLabel(self.tabSearch)
        self.labelAccessTokenSecret.setObjectName("labelAccessTokenSecret")
        self.formLayoutSearch.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelAccessTokenSecret)
        self.lineAccessTokenSecret = QtWidgets.QLineEdit(self.tabSearch)
        self.lineAccessTokenSecret.setObjectName("lineAccessTokenSecret")
        self.formLayoutSearch.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineAccessTokenSecret)
        self.labelConsumerKey = QtWidgets.QLabel(self.tabSearch)
        self.labelConsumerKey.setObjectName("labelConsumerKey")
        self.formLayoutSearch.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelConsumerKey)
        self.lineConsumerKey = QtWidgets.QLineEdit(self.tabSearch)
        self.lineConsumerKey.setObjectName("lineConsumerKey")
        self.formLayoutSearch.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineConsumerKey)
        self.labelConsumerSecret = QtWidgets.QLabel(self.tabSearch)
        self.labelConsumerSecret.setObjectName("labelConsumerSecret")
        self.formLayoutSearch.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelConsumerSecret)
        self.lineConsumerSecret = QtWidgets.QLineEdit(self.tabSearch)
        self.lineConsumerSecret.setObjectName("lineConsumerSecret")
        self.formLayoutSearch.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineConsumerSecret)
        self.pushButtonDatabasePathSearch = QtWidgets.QPushButton(self.tabSearch)
        self.pushButtonDatabasePathSearch.setObjectName("pushButtonDatabasePathSearch")
        self.formLayoutSearch.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButtonDatabasePathSearch)
        self.lineDatabasePathSearch = QtWidgets.QLineEdit(self.tabSearch)
        self.lineDatabasePathSearch.setObjectName("lineDatabasePathSearch")
        self.formLayoutSearch.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineDatabasePathSearch)
        self.labelSearchTerms = QtWidgets.QLabel(self.tabSearch)
        self.labelSearchTerms.setObjectName("labelSearchTerms")
        self.formLayoutSearch.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelSearchTerms)
        self.lineSearchTerms = QtWidgets.QLineEdit(self.tabSearch)
        self.lineSearchTerms.setObjectName("lineSearchTerms")
        self.formLayoutSearch.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineSearchTerms)
        self.verticalLayout_2.addLayout(self.formLayoutSearch)
        self.textEditOutput = QtWidgets.QTextEdit(self.tabSearch)
        self.textEditOutput.setEnabled(True)
        self.textEditOutput.setReadOnly(True)
        self.textEditOutput.setObjectName("textEditOutput")
        self.verticalLayout_2.addWidget(self.textEditOutput)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelFound = QtWidgets.QLabel(self.tabSearch)
        self.labelFound.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelFound.setObjectName("labelFound")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelFound)
        self.lineEditFound = QtWidgets.QLineEdit(self.tabSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFound.sizePolicy().hasHeightForWidth())
        self.lineEditFound.setSizePolicy(sizePolicy)
        self.lineEditFound.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditFound.setReadOnly(True)
        self.lineEditFound.setClearButtonEnabled(False)
        self.lineEditFound.setObjectName("lineEditFound")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditFound)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchPushButtonSearch = QtWidgets.QPushButton(self.tabSearch)
        self.searchPushButtonSearch.setCheckable(False)
        self.searchPushButtonSearch.setChecked(False)
        self.searchPushButtonSearch.setAutoDefault(False)
        self.searchPushButtonSearch.setDefault(False)
        self.searchPushButtonSearch.setFlat(False)
        self.searchPushButtonSearch.setObjectName("searchPushButtonSearch")
        self.horizontalLayout_3.addWidget(self.searchPushButtonSearch)
        self.cancelPushButtonSearch = QtWidgets.QPushButton(self.tabSearch)
        self.cancelPushButtonSearch.setObjectName("cancelPushButtonSearch")
        self.horizontalLayout_3.addWidget(self.cancelPushButtonSearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tabSearch, "")
        self.tabExport = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabExport.sizePolicy().hasHeightForWidth())
        self.tabExport.setSizePolicy(sizePolicy)
        self.tabExport.setObjectName("tabExport")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabExport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayoutExport = QtWidgets.QFormLayout()
        self.formLayoutExport.setObjectName("formLayoutExport")
        self.pushButtonDatabasePathExport = QtWidgets.QPushButton(self.tabExport)
        self.pushButtonDatabasePathExport.setObjectName("pushButtonDatabasePathExport")
        self.formLayoutExport.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButtonDatabasePathExport)
        self.lineDatabasePathExport = QtWidgets.QLineEdit(self.tabExport)
        self.lineDatabasePathExport.setObjectName("lineDatabasePathExport")
        self.formLayoutExport.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineDatabasePathExport)
        self.labelFieldsExport = QtWidgets.QLabel(self.tabExport)
        self.labelFieldsExport.setObjectName("labelFieldsExport")
        self.formLayoutExport.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelFieldsExport)
        self.lineFieldsExport = QtWidgets.QLineEdit(self.tabExport)
        self.lineFieldsExport.setObjectName("lineFieldsExport")
        self.formLayoutExport.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineFieldsExport)
        self.labelLanguagesExport = QtWidgets.QLabel(self.tabExport)
        self.labelLanguagesExport.setObjectName("labelLanguagesExport")
        self.formLayoutExport.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelLanguagesExport)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxAll = QtWidgets.QCheckBox(self.tabExport)
        self.checkBoxAll.setChecked(True)
        self.checkBoxAll.setTristate(False)
        self.checkBoxAll.setObjectName("checkBoxAll")
        self.horizontalLayout.addWidget(self.checkBoxAll)
        self.lineEditLanguages = QtWidgets.QLineEdit(self.tabExport)
        self.lineEditLanguages.setEnabled(False)
        self.lineEditLanguages.setObjectName("lineEditLanguages")
        self.horizontalLayout.addWidget(self.lineEditLanguages)
        self.formLayoutExport.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.labelTable = QtWidgets.QLabel(self.tabExport)
        self.labelTable.setObjectName("labelTable")
        self.formLayoutExport.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelTable)
        self.comboBoxSelectTable = QtWidgets.QComboBox(self.tabExport)
        self.comboBoxSelectTable.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxSelectTable.setObjectName("comboBoxSelectTable")
        self.formLayoutExport.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxSelectTable)
        self.labelFormat = QtWidgets.QLabel(self.tabExport)
        self.labelFormat.setObjectName("labelFormat")
        self.formLayoutExport.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelFormat)
        self.comboBoxSelectFormat = QtWidgets.QComboBox(self.tabExport)
        self.comboBoxSelectFormat.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxSelectFormat.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxSelectFormat.setObjectName("comboBoxSelectFormat")
        self.comboBoxSelectFormat.addItem("")
        self.comboBoxSelectFormat.addItem("")
        self.formLayoutExport.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBoxSelectFormat)
        self.verticalLayout.addLayout(self.formLayoutExport)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exportPushButtonExport = QtWidgets.QPushButton(self.tabExport)
        self.exportPushButtonExport.setCheckable(False)
        self.exportPushButtonExport.setChecked(False)
        self.exportPushButtonExport.setAutoDefault(False)
        self.exportPushButtonExport.setDefault(False)
        self.exportPushButtonExport.setFlat(False)
        self.exportPushButtonExport.setObjectName("exportPushButtonExport")
        self.horizontalLayout_2.addWidget(self.exportPushButtonExport)
        self.cancelPushButtonExport = QtWidgets.QPushButton(self.tabExport)
        self.cancelPushButtonExport.setObjectName("cancelPushButtonExport")
        self.horizontalLayout_2.addWidget(self.cancelPushButtonExport)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabExport, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tweet Watcher"))
        self.labelAccessToken.setText(_translate("MainWindow", "Access Token:"))
        self.labelAccessTokenSecret.setText(_translate("MainWindow", "Access Token Secret:"))
        self.labelConsumerKey.setText(_translate("MainWindow", "Consumer Key:"))
        self.labelConsumerSecret.setText(_translate("MainWindow", "Consumer Secret:"))
        self.pushButtonDatabasePathSearch.setText(_translate("MainWindow", "SQLite3 Database path:"))
        self.labelSearchTerms.setText(_translate("MainWindow", "Search terms:"))
        self.lineSearchTerms.setPlaceholderText(_translate("MainWindow", "comma separated terms, e.g. \"Trump,Bernie\" (without quotation marks)"))
        self.labelFound.setText(_translate("MainWindow", "Found:"))
        self.searchPushButtonSearch.setText(_translate("MainWindow", "Search"))
        self.cancelPushButtonSearch.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("MainWindow", "Search"))
        self.pushButtonDatabasePathExport.setText(_translate("MainWindow", "SQLite3 Database path:"))
        self.labelFieldsExport.setText(_translate("MainWindow", "Fields:"))
        self.lineFieldsExport.setPlaceholderText(_translate("MainWindow", "created_at, user.screen_name, retweeted_status.user.screen_name and text are in by default."))
        self.labelLanguagesExport.setText(_translate("MainWindow", "Languages:"))
        self.checkBoxAll.setText(_translate("MainWindow", "All"))
        self.lineEditLanguages.setPlaceholderText(_translate("MainWindow", "pt,en"))
        self.labelTable.setText(_translate("MainWindow", "Table:"))
        self.labelFormat.setText(_translate("MainWindow", "Format:"))
        self.comboBoxSelectFormat.setItemText(0, _translate("MainWindow", ".xlsx"))
        self.comboBoxSelectFormat.setItemText(1, _translate("MainWindow", ".csv"))
        self.exportPushButtonExport.setText(_translate("MainWindow", "Export"))
        self.cancelPushButtonExport.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExport), _translate("MainWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
